[package]
name = "sync-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
proxy-server = { path = "../proxy-server", version="0.4.2" }
serde_json = "1.0.108"

[build-dependencies]
napi-build = "1"
